[package]
name = "rs-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = "0.25.0"
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
solana-program = "1.10"
hex="0.4.3"
anyhow="1.0.58"
async-trait="0.1.57"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.9.16"

tracing = { version = "0.1.35", features = ["log"] }
tracing-bunyan-formatter = "0.3.3"
tracing-subscriber = { version = "0.3.14", features = ["registry", "env-filter"] }
borsh = "0.9.3"
pad = "0.1.6"

multisig = {path="../../programs/multisig"}
# mockprogram = {path="../mockprogram/programs/mockprogram"}
