[package]
name = "rs-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.0.29", features=["derive"]}
rs-sdk = {path="../rs-sdk"}
console = "0.15.2"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.9.16"
anchor-client = "0.25.0"